/**
 * PDF Report Generator
 * Generates PDF reports for Impact Analysis
 * Uses html2canvas and jsPDF for client-side PDF generation
 */

export interface PDFReportData {
  title: string;
  siteName: string;
  dateRange: string;
  kpis: {
    netDailySavings: number;
    batteryLifeImpact: number;
    renewableUtilization: number;
    carbonAvoided: number;
  };
  comparisonMode: string;
  insights: Array<{
    title: string;
    description: string;
  }>;
  charts?: Array<{
    title: string;
    dataUrl: string; // base64 image
  }>;
}

export const generateImpactPDF = async (data: PDFReportData): Promise<void> => {
  try {
    // Dynamic import to avoid loading heavy libraries unless needed
    const html2canvas = (await import('html2canvas')).default;
    const jsPDF = (await import('jspdf')).default;

    // Create a temporary container for the report
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.width = '210mm'; // A4 width
    container.style.padding = '20mm';
    container.style.backgroundColor = '#ffffff';
    container.style.fontFamily = 'Arial, sans-serif';
    document.body.appendChild(container);

    // Build HTML content
    container.innerHTML = `
      <div style="margin-bottom: 30px;">
        <h1 style="color: #1e40af; font-size: 28px; margin-bottom: 10px;">${data.title}</h1>
        <p style="color: #6b7280; font-size: 14px;">Site: ${data.siteName} | Period: ${data.dateRange}</p>
      </div>

      <div style="margin-bottom: 30px; display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px;">
        <div style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 20px; border-radius: 8px;">
          <p style="font-size: 12px; margin-bottom: 5px; opacity: 0.9;">Net Daily Savings</p>
          <p style="font-size: 24px; font-weight: bold;">₹${data.kpis.netDailySavings.toLocaleString()}</p>
        </div>
        <div style="background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%); color: white; padding: 20px; border-radius: 8px;">
          <p style="font-size: 12px; margin-bottom: 5px; opacity: 0.9;">Battery Life Impact</p>
          <p style="font-size: 24px; font-weight: bold;">${data.kpis.batteryLifeImpact.toFixed(2)}%</p>
        </div>
        <div style="background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%); color: white; padding: 20px; border-radius: 8px;">
          <p style="font-size: 12px; margin-bottom: 5px; opacity: 0.9;">Renewable Utilization</p>
          <p style="font-size: 24px; font-weight: bold;">${data.kpis.renewableUtilization.toFixed(1)}%</p>
        </div>
        <div style="background: linear-gradient(135deg, #14b8a6 0%, #0d9488 100%); color: white; padding: 20px; border-radius: 8px;">
          <p style="font-size: 12px; margin-bottom: 5px; opacity: 0.9;">Carbon Avoided</p>
          <p style="font-size: 24px; font-weight: bold;">${data.kpis.carbonAvoided.toFixed(1)} kg CO₂</p>
        </div>
      </div>

      <div style="margin-bottom: 30px;">
        <h2 style="color: #1e40af; font-size: 20px; margin-bottom: 15px;">Key Insights</h2>
        ${data.insights
          .map(
            (insight, index) => `
          <div style="background: #f3f4f6; padding: 15px; border-radius: 8px; margin-bottom: 10px; border-left: 4px solid #3b82f6;">
            <p style="font-weight: bold; color: #1f2937; margin-bottom: 5px;">${index + 1}. ${insight.title}</p>
            <p style="color: #4b5563; font-size: 14px; line-height: 1.6;">${insight.description}</p>
          </div>
        `
          )
          .join('')}
      </div>

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; text-align: center;">
        <p>Generated by VidyutAI Intelligent EMS</p>
        <p>Comparison Mode: ${data.comparisonMode}</p>
        <p>Generated on: ${new Date().toLocaleString()}</p>
      </div>
    `;

    // Convert to canvas
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
    });

    // Create PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;

    let position = 0;

    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Clean up
    document.body.removeChild(container);

    // Download PDF
    pdf.save(`VidyutAI-Impact-Report-${data.siteName}-${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    // Fallback: Show alert if libraries aren't available
    alert('PDF generation requires additional libraries. Please install html2canvas and jspdf.');
  }
};

